### ISSUE TITLE
[BUG] Version 0.42 - Kit Shop Page Number

### ISSUE THREAD

**Issue by gloandrew** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#28]
The page number below the kit shop is repeated.
Please refer to the image below to see the problem,

Expected Result:
The page number in the "Kit Shop" doesn't repeat itself.

![no 16 kit shop page number](https://user-images.githubusercontent.com/33440645/32598841-555adb08-c56d-11e7-9e33-2dd387a6fc46.jpg)

Thank you

**Comment by MattheusRossopIII** [comment]
Fixed for v1.0.17g, version code 47 of Android build.

**Comment by ErwinGL1** [comment]
This issue still occured, same with #29 

After the install, I will go to settings > click like us > after go to browser, and back to the game, it will re-loading, after the loading done, this bugs will occured with #29 and also attributes when you raising stats or reset the stats

**Comment by gloandrew** [comment]
Version 0.47

Hi team, 
The page numbers on the Kit Shop still repeats itself in the latest version.

How to recreate the bug:
I just go in the game and it straight up have that error.

Expected result:
The page on the kit shop doesn't repeat.

Please refer to the link below to look at the problem:
https://drive.google.com/open?id=1JT39IO91ljqL3hCKnrPBvyYXzuuf9fi_

Thank you

**Comment by farahliany** [comment]
This issue has been solved.
